FROM centos:8
RUN yum install -y openssh-server
RUN echo 'root:zaqxswcde' | chpasswd
RUN ssh-keygen -A
RUN sed 's/^\(#\|P\).*RootLogin.*/PermitRootLogin yes/' /etc/ssh/sshd_config -i
RUN sed 's/^\(#\|P\).*Authentication.*/PasswordAuthentication yes/' /etc/ssh/sshd_config -i
RUN sed 's/^session.*pam_loginuid.so$/session\toptional\tpam_loginuid.so/'  /etc/pam.d/sshd -i
RUN rm /run/nologin
CMD  ["/usr/sbin/sshd", "-D"]
