version: "3"

services:
  db1:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=
      - MYSQL_DATABASE=ghost
  ghost:
    image: ghost:latest
    ports:
      - "80:2368"
    environment:
      - database__client=mysql
      - database__connection__host=
      - database__connection__user=ghost
      - database__connection__password=
      - database__connection__database=ghost
      - url=http://10.254.1.28:80
    depends_on:
      - db1
