version: '3'

services: 
    jenkins:
        image: jenkins/jenkins
        container_name: jenkins
        ports:
            - '8080:8080'
            - '50000:50000'
        volumes:
            - jenkins_dir:/var/jenkins_home
        restart: unless-stopped
           
volumes:
    jenkins_dir: