version: "3"

services:
    database:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        container_name: ${WORDPRESS_DB_CONTAINER_NAME}
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_DATABASE=${WORDPRESS_DATABASE}
            - MYSQL_USER=${WORDPRESS_USER}
            - MYSQL_PASSWORD=${WORDPRESS_PASSWORD}
        volumes:
            - mysql_wordpress_dir:/var/lib/mysql
        networks:
            - mysql_private
        restart: unless-stopped

    webcontent:
        image: wordpress
        container_name: wordpress
        ports:
            - "8081:80"
        environment:
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_CONTAINER_NAME}
            - WORDPRESS_DB_USER=${WORDPRESS_USER}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_PASSWORD}
            - WORDPRESS_DB_NAME=${WORDPRESS_DATABASE}
        volumes:
            - wordpress_dir:/var/www/html
        networks:
            - wordpress_net
            - mysql_private
        restart: unless-stopped
        depends_on:
            - database

volumes:
    mysql_wordpress_dir:
    wordpress_dir:

networks:
    mysql_private:
        driver: bridge
    wordpress_net:
        driver: bridge
