version: "3"

services:
    database:
        image: mysql:latest
        command: --default-authentication-plugin=mysql_native_password
        environment:
            - MYSQL_ROOT_PASSWORD=${WORDPRESS_DB_CONTAINER_NAME}
            - MYSQL_DATABASE=${WORDPRESS_DB_CONTAINER_NAME}
            - MYSQL_USER=${WORDPRESS_DB_CONTAINER_NAME}
            - MYSQL_PASSWORD=${WORDPRESS_DB_CONTAINER_NAME}
        networks:
            - mysql_private
        volumes:
            - mysql_wordpress_dir:/var/lib/mysql
        restart: unless-stopped

    webcontent:
        image: wordpress
        ports:
            - "8081:80"
        environment:
            - WORDPRESS_DB_HOST=${WORDPRESS_DB_CONTAINER_NAME}
            - WORDPRESS_DB_USER=${WORDPRESS_DB_CONTAINER_NAME}
            - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_CONTAINER_NAME}
            - WORDPRESS_DB_NAME=${WORDPRESS_DB_CONTAINER_NAME}
        networks:
            - bridge
            - mysql_private
        volumes:
            - wordpress_dir:/var/www/html
        restart: unless-stopped
        depends_on:
            - database

volumes:
    mysql_wordpress_dir:
    wordpress_dir:

networks:
    mysql_private:
        driver: overlay
    bridge:
        external:
            name: bridge
