apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress-db
  name: wordpress-db-svc
spec:
  ports:
    - name: wordpress-db-svc
      port: 3306
      protocol: TCP
  selector:
    app: wordpress-db
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-db
  labels:
    app: wordpress-db
spec:
  selector:
    matchLabels:
      app: wordpress-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: wordpress-db
    spec:
      containers:
        - image: mysql
          args: ["--default-authentication-plugin=mysql_native_password"]
          name: mysql-container
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db_root_password
            - name: MYSQL_DATABASE
              value: wordpress
            - name: MYSQL_USER
              value: wordpress
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: wordpress-secret
                  key: db_wordpress_password
          ports:
            - containerPort: 3306
              name: mysql-container
#          volumeMounts:
#          #            - name: mysql-persistent-storage
#          #              mountPath: /var/lib/mysql
#          #      volumes:
#          #        - name: mysql-persistent-storage
#          #          persistentVolumeClaim:
#          #            claimName: mysql-pv-claim
#
#
